version: 2
updates:
  - package-ecosystem: "bundler" # Ruby dependencies
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions" # GitHub Actions workflows
    directory: "/"
    schedule:
      interval: "weekly"
