version: '3'
services:
  bot:
    image: ghcr.io/quintasan/discord-preview-fixer:v1.3.8
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISCORD_PREVIEW_FIXER_TOKEN:
      SENTRY_DSN:
      SENTRY_ENVIRONMENT:
      SENTRY_RELEASE: v1.3.8
      DISCORDRB_NONACL: true # makes it shut up about missign libsodium
      DB_PATH: /app/db/messages.db
    volumes:
      - db:/app/db
    restart: unless-stopped

volumes:
  db: