version: '3'
services:
  bot:
    image: ghcr.io/quintasan/discord-preview-fixer:${IMAGE_TAG:-v1.5.0}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISCORD_PREVIEW_FIXER_TOKEN:
      SENTRY_DSN:
      SENTRY_ENVIRONMENT:
      SENTRY_RELEASE: ${IMAGE_TAG:-v1.5.0}
      DISCORDRB_NONACL: true # makes it shut up about missign libsodium
      DB_PATH: /app/db/messages.db
      HEALTHCHECK_PORT: 8080
    volumes:
      - db:/app/db
    restart: unless-stopped

volumes:
  db:
